### ISSUE TITLE
Tests to-do-list

### ISSUE THREAD

**Issue by jonasvannijnatten** [jonasvannijnatten/Overview-statistic-tests#1]
post-hoc tests
- [x] Independent samples one-way ANOVA
- [x] Repeated measures one-way ANOVA

non-parametric alternatives
- [ ] Independent samples T-test
- [ ] Paired samples T-test
- [ ] Independent samples one-way ANOVA
- [ ] Repeated measures one-way ANOVA
